require 'minitest/autorun'
#require_relative './unit/scan_test'
#require_relative './unit/ttg_pca_test'
#require_relative './unit/calc_intercept_test'
#require_relative './unit/collision_test'
#require_relative './unit/munition_expiration_test'
#require_relative './unit/shortest_turn_test'
